config/routes.rb
SelarzSarbaz::Application.routes.draw do

  get 'firm-overview' => 'static_pages#firm_overview', as: :overview

  root 'static_pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
	end

	def firm_overview
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer">
   <!-- Footer Top Start -->
   <div class="footer-top">
      <div class="container">
         <div class="row">
            <section class="col-lg-4 col-md-4 col-xs-12 col-sm-4 footer-one">
               <h3>About Us</h3>
               <p> 
                  We are an elite team of ninja lawyers ready to serve you. Pick up the phone, and call us. 
               </p>
            </section>
            <section class="col-lg-4 col-md-4 col-xs-12 col-sm-4 footer-three">
               <h3>Contact Us</h3>
               <ul class="contact-us">
                  <li>
                     <i class="fa fa-map-marker"></i>
                     <p> 
                        <strong>Address:</strong>9701 Wilshire Boulevard<br>
                        Beverly Hills, California 90212
                     </p>
                  </li>
                  <li>
                     <i class="fa fa-phone"></i>
                     <p><strong>Phone:</strong> (310) 651-8685</p>
                  </li>
                  <li>
                     <i class="fa fa-envelope-o"></i>
                     <p><strong>Email:</strong><a href="mailto:info@fifothemes.com">info@fifothemes.com</a></p>
                  </li>
               </ul>
            </section>
         </div>
      </div>
   </div>
   <!-- Footer Top End --> 
</footer>

app/views/layouts/_header.html.erb
<header id="header">
   <!-- Main Header Start -->
   <div class="main-header">
      <div class="container">
         
         <!-- Logo Start -->
         <div class="logo pull-left">
            <h1>
              <%= link_to image_tag("logo.png", alt: "pixma", width: "125", height: "60"), root_path %> 
            </h1>
         </div>
         <!-- Logo End -->

         <!-- Mobile Menu Start -->
         <div class="mobile navbar-header">
            <a class="navbar-toggle" data-toggle="collapse" href=".navbar-collapse">
            <i class="fa fa-bars fa-2x"></i>
            </a> 
         </div>
         <!-- Mobile Menu End -->
         
         <!-- Menu Start -->
         <nav class="collapse navbar-collapse menu">
            <ul class="nav navbar-nav sf-menu">
               <li>
                  <%= link_to "Firm Overview", overview_path %>
               </li>
               <li>
                  <a href="#" class="sf-with-ul">
                  Features 
                  <span class="sf-sub-indicator">
                  <i class="icon-angle-down "></i>
                  </span>
                  </a>
                  <ul>
                     <li><a href="shortcodes.html" class="sf-with-ul">Shortcodes</a></li>
                     <li><a href="icons.html" class="sf-with-ul">Icons</a></li>
                     <li><a href="pricing-table.html" class="sf-with-ul">Pricing Tables</a></li>
                     <li>
                        <a href="#" class="sf-with-ul"> 
                        Third Level Menu 
                        <span class="sf-sub-indicator pull-right">
                        <i class="icon-angle-right "></i>
                        </span>
                        </a>
                        <ul>
                           <li><a href="#" class="sf-with-ul">Menu Item</a></li>
                           <li><a href="#" class="sf-with-ul">Menu Item</a></li>
                           <li><a href="#" class="sf-with-ul">Menu Item</a></li>
                        </ul>
                     </li>
                  </ul>
               </li>
               <li>
                  <a href="#" class="sf-with-ul">
                  Pages
                  <span class="sf-sub-indicator">
                  <i class="icon-angle-down "></i>
                  </span>
                  </a>
                  <ul>
                     <li><a href="about.html" class="sf-with-ul">About Us</a></li>
                     <li><a href="services.html" class="sf-with-ul">Services</a></li>
                     <li><a href="testimonials.html" class="sf-with-ul">Testimonials</a></li>
                     <li><a href="full-width.html" class="sf-with-ul">Full Width Page</a></li>
                     <li><a href="page-left-sidebar.html" class="sf-with-ul">Left Sidebar</a></li>
                     <li><a href="page-right-sidebar.html" class="sf-with-ul">Right Sidebar</a></li>
                     <li><a href="page-left-navigation.html" class="sf-with-ul">Left Navigation</a></li>
                     <li><a href="page-right-navigation.html" class="sf-with-ul">Right Navigation</a></li>
                     <li><a href="faq.html" class="sf-with-ul">FAQ</a></li>
                     <li><a href="page-404.html" class="sf-with-ul">404 Page</a></li>
                     <li><a href="sitemap.html" class="sf-with-ul">Sitemap</a></li>
                  </ul>
               </li>
               <li>
                  <a href="#" class="sf-with-ul">
                  Portfolio
                  <span class="sf-sub-indicator">
                  <i class="icon-angle-down "></i>
                  </span>
                  </a>
                  <ul>
                     <li><a href="portfolio-two.html" class="sf-with-ul">2 Column</a></li>
                     <li><a href="portfolio-three.html" class="sf-with-ul">3 Column</a></li>
                     <li><a href="portfolio-four.html" class="sf-with-ul">4 Column</a></li>
                     <li><a href="portfolio-single.html" class="sf-with-ul">Single Item Page</a></li>
                     <li><a href="portfolio-single-big.html" class="sf-with-ul">Single Large Item Page</a></li>
                  </ul>
               </li>
               <li>
                  <a href="#" class="sf-with-ul">
                  Blog
                  <span class="sf-sub-indicator">
                  <i class="icon-angle-down "></i>
                  </span>
                  </a>
                  <ul>
                     <li><a href="blog-left-sidebar.html" class="sf-with-ul">Left Sidebar Blog</a></li>
                     <li><a href="blog-right-sidebar.html" class="sf-with-ul">Right Sidebar Blog</a></li>
                     <li><a href="blog-small.html" class="sf-with-ul">Small Blog</a></li>
                     <li><a href="single-post.html" class="sf-with-ul">Single Post</a></li>
                  </ul>
               </li>
               <li><a href="contact.html">Contact</a></li>
            </ul>
         </nav>
         <!-- Menu End -->

      </div>
   </div>
   <!-- Main Header End -->
</header>

app/views/layouts/_scripts.html.erb
<script src="assets/jquery.min.js"></script>
<script src="assets/bootstrap.js"></script>
<script src="assets/jquery.parallax.js"></script> 
<script src="assets/modernizr-2.6.2.min.js"></script> 
<script src="assets/revolution-slider/js/jquery.themepunch.revolution.min.js"></script>
<script src="assets/jquery.nivo.slider.pack.js"></script>
<script src="assets/jquery.prettyPhoto.js"></script>
<script src="assets/superfish.js"></script>
<script src="assets/tweetMachine.js"></script>
<script src="assets/tytabs.js"></script>
<script src="assets/jquery.gmap.min.js"></script>
<script src="assets/circularnav.js"></script>
<script src="assets/jquery.sticky.js"></script>
<script src="assets/jflickrfeed.js"></script>
<script src="assets/imagesloaded.pkgd.min.js"></script>
<script src="assets/waypoints.min.js"></script>
<script src="assets/custom.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>			<html class="ie ie8"> <![endif]-->
<!--[if IE 9]>			<html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->	<html> <!--<![endif]-->

<head>
  <title>Selarz & Sarbaz, LLC</title>
  <meta charset="utf-8">
  <meta name="description" content="Selarz & Sarbaz Law Practice">
  <meta name="author" content="Daniel Selarz, Ary Sarbaz">
  <!-- Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
 	<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<script src="js/respond.min.js"></script>
  <![endif]-->
  <!--[if IE]>
  <link rel="stylesheet" href="css/ie.css">
  <![endif]-->
</head>
	
	<body class="home">

		<%= render 'layouts/header' %>

		<div class="wrap">
			<%= yield %>
		</div>

		<%= render 'layouts/footer' %>
	</body>

	<%= render 'layouts/scripts' %>
</html>

app/views/static_pages/firm_overview.html.erb
<!-- Content Start -->
<div id="main">
   <!-- Title, Breadcrumb Start-->
   <div class="breadcrumb-wrapper">
      <div class="container">
         <div class="row">
            <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6">
               <h2 class="title">Firm Overview</h2>
            </div>
            <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6">
               <div class="breadcrumbs pull-right">
                  <ul>
                     <li>You are here:</li>
                     <li><%= link_to "Home", root_path %></li>
                     <li>Firm Overview</li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- Title, Breadcrumb End-->
   <!-- Main Content start-->
   <div class="content">
      <div class="container">
         <div class="row">
            <div class="posts-block col-lg-12 col-md-12 col-sm-12 col-xs-12">
               <article>
                  <h3 class="title">A Message from Ary and Daniel</h3>
                  <div class="post-content">
                     <p>
                        There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
                     </p>
                     <br>
                     <p>
                        There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
                     </p>
                     <br>
                     <p>
                        There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
                     </p>
                     <br>
                     <p>
                        There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
                     </p>
                  </div>
               </article>
            </div>
            <!-- Left Section End -->
         </div>
      </div>
   </div>
   <!-- Main Content end-->
</div>